/**
 * Copyright (c) 2025 Comunidad de Madrid & Alastria
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Reproduces the on-chain acceptance check so a proof that the registry would
 * reject fails here instead of on a reverted transaction.
 *
 * Mirrors `DidDocumentDetailedInternal._validateProof` (isbe-contracts):
 *
 *   recovered = ecrecover(keccak256(_publicKey), _proof)
 *   require(recovered == _getAddress(_publicKey))
 *
 * Note the asymmetry in the Solidity: the digest hashes `_publicKey` RAW,
 * while `_getAddress` runs it through `_sanitizePublicKey` first, which
 * strips a leading 0x04. So the two agree only when the public key reaches
 * the contract as 64 bytes. See the 65-byte test below.
 *
 * Only secp256k1 is covered: `_recoverSigner` uses `ecrecover`, which on the
 * Case Network is secp256k1. The Bare Network gets the same opcode bound to
 * P-256 via the Besu genesis, and is out of scope here.
 */

import { keccak256, recoverAddress } from "ethers";
import vectors from "./fixtures/golden-vectors.json";
import { generateProof } from "../commands/did";
import { publicKeyToEOA } from "../utils";

type Vector = {
  curve: string;
  privateKey: string;
  proof: string;
  publicKey: string;
  eoa: string;
};

const K1 = (vectors as unknown as Vector[]).filter(
  (v) => v.curve === "secp256k1",
);

/** `_splitSignature` in core/signatureVerification.sol. */
function splitSignature(proof: string) {
  const raw = proof.replace(/^0x/, "");
  if (raw.length !== 130) throw new Error("WrongSignatureLength");
  return {
    r: "0x" + raw.slice(0, 64),
    s: "0x" + raw.slice(64, 128),
    v: parseInt(raw.slice(128, 130), 16),
  };
}

/** `_sanitizePublicKey` in DidDocumentDetailedInternal.sol. */
function sanitizePublicKey(publicKey: string): string {
  const raw = publicKey.replace(/^0x/, "");
  if (raw.length === 130) {
    if (!raw.startsWith("04")) throw new Error("InvalidControlBytes");
    return "0x" + raw.slice(2);
  }
  if (raw.length === 128) return "0x" + raw;
  throw new Error("InvalidPubKeyLength");
}

/** `_validateProof`, returning the recovered signer and the expected owner. */
function validateProof(publicKeyAsSentOnChain: string, proof: string) {
  const recovered = recoverAddress(
    keccak256(publicKeyAsSentOnChain),
    splitSignature(proof),
  );
  return { recovered, sanitized: sanitizePublicKey(publicKeyAsSentOnChain) };
}

describe("registry acceptance (_validateProof)", () => {
  it.each(K1.map((v) => [v.privateKey.slice(0, 10), v] as const))(
    "%s: proof is accepted when the public key is sent as 64 bytes",
    async (_label, v) => {
      const publicKey64 = sanitizePublicKey(v.publicKey);
      const { recovered } = validateProof(publicKey64, v.proof);
      const owner = await publicKeyToEOA(publicKey64);

      expect(recovered).toBe(owner);
      expect(recovered).toBe(v.eoa);
    },
  );

  it.each(K1.map((v) => [v.privateKey.slice(0, 10), v] as const))(
    "%s: proof is REJECTED when the public key is sent as 65 bytes",
    (_label, v) => {
      // Guard rail, not a wish: `_validateProof` hashes the public key raw,
      // so the 0x04 prefix changes the digest and the recovered address no
      // longer matches the owner. If this ever starts passing, the contract
      // changed and the CLI's output needs revisiting.
      const { recovered } = validateProof(v.publicKey, v.proof);
      expect(recovered).not.toBe(v.eoa);
    },
  );

  it("a proof from a different key is rejected", () => {
    const [a, b] = K1;
    const publicKey64 = sanitizePublicKey(a.publicKey);
    const { recovered } = validateProof(publicKey64, b.proof);
    expect(recovered).not.toBe(a.eoa);
  });

  it("a tampered proof does not recover the owner", () => {
    const v = K1[0];
    const publicKey64 = sanitizePublicKey(v.publicKey);
    const tampered =
      v.proof.slice(0, -4) + (v.proof.slice(-4, -2) === "ff" ? "00" : "ff") + v.proof.slice(-2);
    const { recovered } = validateProof(publicKey64, tampered);
    expect(recovered).not.toBe(v.eoa);
  });

  it("proofs regenerated by the current code still satisfy the contract", async () => {
    for (const v of K1) {
      const proof = generateProof(v.privateKey, "secp256k1");
      const publicKey64 = sanitizePublicKey(v.publicKey);
      const { recovered } = validateProof(publicKey64, proof);
      expect(recovered).toBe(await publicKeyToEOA(publicKey64));
    }
  });

  it("rejects malformed proof lengths the way _splitSignature does", () => {
    expect(() => splitSignature("0x1234")).toThrow("WrongSignatureLength");
  });

  it("rejects public key lengths the way _sanitizePublicKey does", () => {
    expect(() => sanitizePublicKey("0x" + "11".repeat(33))).toThrow(
      "InvalidPubKeyLength",
    );
    expect(() => sanitizePublicKey("0x05" + "11".repeat(64))).toThrow(
      "InvalidControlBytes",
    );
  });
});
